export const PermissionCode = {
  UsersCreate: "usersCreate",
  UsersUpdate: "usersUpdate",
  UsersDelete: "usersDelete",
  UsersAuthorize: "usersAuthorize",
  PermissionsCreate: "permissionsCreate",
  PermissionsUpdate: "permissionsUpdate",
  PermissionsDelete: "permissionsDelete",
  OrganizationsCreate: "organizationsCreate",
  OrganizationsUpdate: "organizationsUpdate",
  OrganizationsDelete: "organizationsDelete",
  DataDictionariesCreate: "dataDictionariesCreate",
  DataDictionariesUpdate: "dataDictionariesUpdate",
  DataDictionariesDelete: "dataDictionariesDelete",
} as const;
