export const PermissionCode = {
  UsersCreate: "usersCreate",
  UsersUpdate: "usersUpdate",
  UsersDelete: "usersDelete",
  UsersAuthorize: "usersAuthorize",
  UsersResetPassword: "usersResetPassword",
  PermissionsCreate: "permissionsCreate",
  PermissionsUpdate: "permissionsUpdate",
  PermissionsDelete: "permissionsDelete",
  OrganizationsCreate: "organizationsCreate",
  OrganizationsUpdate: "organizationsUpdate",
  OrganizationsDelete: "organizationsDelete",
  DataDictionariesCreate: "dataDictionariesCreate",
  DataDictionariesUpdate: "dataDictionariesUpdate",
  DataDictionariesDelete: "dataDictionariesDelete",
  ProductCategoriesCreate: "productCategoriesCreate",
  ProductCategoriesUpdate: "productCategoriesUpdate",
  ProductCategoriesDelete: "productCategoriesDelete",
} as const;
